import re
from typing import Generator, Callable

def generator_numbers(text: str) -> Generator[float, None, None]:
    """Generates numbers from the given text."""

    pattern = r'\b(\d+\.?\d*)\b'
    matches = re.finditer(pattern, text)
    for match in matches:
        yield float(match.group(1))

def sum_profit(text: str, func: Callable[[str], Generator[float, None, None]]) -> float:
    """Calculates the sum of numbers generated by the provided function."""
    
    return sum(func(text))
